# Generated by Django 5.2.3 on 2025-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantities',
            new_name='quantity',
        ),
    ]
