# Generated by Django 5.2.3 on 2025-07-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_food_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_title',
            field=models.CharField(error_messages={'unique': 'A food with this name already exists.'}, max_length=100, unique=True),
        ),
    ]
