# Generated by Django 5.2.4 on 2025-08-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Paystack', 'Paystack'), ('Flutterwave', 'Flutterwave')], default='Visa', max_length=100),
        ),
    ]
